version: '3.8'

services:
  # Servicio de Laravel
  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: laravel_app
    ports:
      - "8001:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - laravel_network
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=blink_sprint4_equip3
      - DB_USERNAME=root
      - DB_PASSWORD=password

  # Servicio de MariaDB
  db:
    image: mariadb:11.2
    container_name: mariadb_blink
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: blink_sprint4_equip3
      MYSQL_USER: blink_sprint4_equip3
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
